# Generated by Django 5.1.4 on 2025-01-03 15:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charger_address', models.CharField(max_length=42, unique=True)),
                ('price_per_kwh', models.IntegerField()),
            ],
            options={
                'db_table': 'charger',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='ServerNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonce', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'nounce',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_address', models.CharField(max_length=42, unique=True)),
                ('balance', models.IntegerField()),
                ('contribution', models.PositiveIntegerField()),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=255)),
                ('nonce', models.IntegerField(default=0)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVCharge.role')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='TransactionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_demand', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount_owed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('charger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_summaries', to='EVCharge.charger')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_summary',
            },
        ),
        migrations.CreateModel(
            name='ChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.IntegerField()),
                ('demand', models.IntegerField()),
                ('is_completed', models.BooleanField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('charger_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EVCharge.charger')),
                ('charger_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charger_sessions', to=settings.AUTH_USER_MODEL)),
                ('client_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'charging_session',
            },
        ),
        migrations.AddField(
            model_name='charger',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargers', to=settings.AUTH_USER_MODEL, to_field='user_address'),
        ),
    ]
