# Generated by Django 5.1.4 on 2025-01-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVCharge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsummary',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
